### ISSUE TITLE
ValueError: height and width must be > 0

### ISSUE THREAD

**Issue by kimlia545** [Belval/TextRecognitionDataGenerator#190]
My version is Python 3.8.5

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 562, in <module>
    main()
  File "run.py", line 492, in main
    for _ in tqdm(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tqdm\std.py", line 1165, in __iter__
    for obj in iterable:
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 868, in next
    raise value
ValueError: height and width must be > 0

**Comment by SaeedArisha** [comment]
@kimlia545 How did you solve this issue?

**Comment by kimlia545** [comment]
@SaeedArisha 
Sorry for the late reply.
Make sure the font or dictionary directory is correct.
If an error occurs, specify an absolute path.
Or Please check if the command is correct.

**Comment by SaeedArisha** [comment]
@kimlia545 Thank you, luckily I had solved it

**Comment by worldofzeroandone** [comment]
@kimlia545 @SaeedArisha 
> Sorry for the late reply.
> Make sure the font or dictionary directory is correct.
> If an error occurs, specify an absolute path.
> Or Please check if the command is correct.

I specify an absolute path of a font dir but still occur this problem,I want generate 450000 images,why?

**Comment by worldofzeroandone** [comment]
> @kimlia545 @SaeedArisha
> 
> > Sorry for the late reply.
> > Make sure the font or dictionary directory is correct.
> > If an error occurs, specify an absolute path.
> > Or Please check if the command is correct.
> 
> I specify an absolute path of a font dir but still occur this problem,I want generate 450000 images,why?

this is my error:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/gxu4090x2/.conda/envs/mm/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/gxu4090x2/桌面/chengang/TRDG/trdg/data_generator.py", line 22, in generate_from_tuple
    cls.generate(*t)
  File "/home/gxu4090x2/桌面/chengang/TRDG/trdg/data_generator.py", line 133, in generate
    resized_img = distorted_img.resize(
  File "/home/gxu4090x2/.conda/envs/mm/lib/python3.8/site-packages/PIL/Image.py", line 2305, in resize
    im = im.resize(size, resample, box)
  File "/home/gxu4090x2/.conda/envs/mm/lib/python3.8/site-packages/PIL/Image.py", line 2328, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 493, in <module>
    main()
  File "run.py", line 438, in main
    for _ in tqdm(
  File "/home/gxu4090x2/.conda/envs/mm/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/gxu4090x2/.conda/envs/mm/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
ValueError: height and width must be > 0
