### ISSUE TITLE
Background with different colors

### ISSUE THREAD

**Issue by yustiks** [Belval/TextRecognitionDataGenerator#203]
added different coloured background generator:
data_generator.py:
```
        elif background_type == 4:
            background_img = background_generator.random_background(
                background_height, background_width
            )
```

background_generator.py:
```

def random_background(height, width):
    """
        Create a random background
    """
    r = np.random.randint(255)
    g = np.random.randint(255)
    b = np.random.randint(255)

    return Image.new("RGB", (width, height), (r, g, b))
```

**Comment by mgersalan** [comment]
Hi, I'm getting an error like this

```

> Missing modules for handwritten text generation.
>   1%|▋                                                                                            | 7/1000 [00:00<01:27, 11.29it/s]multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/multiprocessing/pool.py", line 121, in worker
>     result = (True, func(*args, **kwds))
>   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/trdg/data_generator.py", line 21, in generate_from_tuple
>     cls.generate(*t)
>   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/trdg/data_generator.py", line 171, in generate
>     background_height, background_width, image_dir
>   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/trdg/background_generator.py", line 66, in image
>     os.path.join(image_dir, images[rnd.randint(0, len(images) - 1)])
>   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/PIL/Image.py", line 2959, in open
>     "cannot identify image file %r" % (filename if filename else fp)
> PIL.UnidentifiedImageError: cannot identify image file '/Users/gurersalan/Documents/TextRecognitionDataGenerator/trdg/images/.DS_Store'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "trdg/run.py", line 477, in <module>
>     main()
>   File "trdg/run.py", line 459, in main
>     total=args.count,
>   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/tqdm/_tqdm.py", line 930, in __iter__
>     for obj in iterable:
>   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/multiprocessing/pool.py", line 748, in next
>     raise value
> PIL.UnidentifiedImageError: cannot identify image file '/Users/gurersalan/Documents/TextRecognitionDataGenerator/trdg/images/.DS_Store'
> Exception ignored in: <function tqdm.__del__ at 0x7fd970daa8c0>
> Traceback (most recent call last):
>   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/tqdm/_tqdm.py", line 882, in __del__
>   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1087, in close
>   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/tqdm/_tqdm.py", line 439, in _decr_instances
>   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/_weakrefset.py", line 109, in remove
> KeyError: <weakref at 0x7fd9718f8770; to 'tqdm' at 0x7fd975ae2150>

```

**Comment by yustiks** [comment]
> Hi, I'm getting an error like this
> 
> ```
> 
> > Missing modules for handwritten text generation.
> >   1%|▋                                                                                            | 7/1000 [00:00<01:27, 11.29it/s]multiprocessing.pool.RemoteTraceback: 
> > """
> > Traceback (most recent call last):
> >   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/multiprocessing/pool.py", line 121, in worker
> >     result = (True, func(*args, **kwds))
> >   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/trdg/data_generator.py", line 21, in generate_from_tuple
> >     cls.generate(*t)
> >   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/trdg/data_generator.py", line 171, in generate
> >     background_height, background_width, image_dir
> >   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/trdg/background_generator.py", line 66, in image
> >     os.path.join(image_dir, images[rnd.randint(0, len(images) - 1)])
> >   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/PIL/Image.py", line 2959, in open
> >     "cannot identify image file %r" % (filename if filename else fp)
> > PIL.UnidentifiedImageError: cannot identify image file '/Users/gurersalan/Documents/TextRecognitionDataGenerator/trdg/images/.DS_Store'
> > """
> > 
> > The above exception was the direct cause of the following exception:
> > 
> > Traceback (most recent call last):
> >   File "trdg/run.py", line 477, in <module>
> >     main()
> >   File "trdg/run.py", line 459, in main
> >     total=args.count,
> >   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/tqdm/_tqdm.py", line 930, in __iter__
> >     for obj in iterable:
> >   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/multiprocessing/pool.py", line 748, in next
> >     raise value
> > PIL.UnidentifiedImageError: cannot identify image file '/Users/gurersalan/Documents/TextRecognitionDataGenerator/trdg/images/.DS_Store'
> > Exception ignored in: <function tqdm.__del__ at 0x7fd970daa8c0>
> > Traceback (most recent call last):
> >   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/tqdm/_tqdm.py", line 882, in __del__
> >   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1087, in close
> >   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/site-packages/tqdm/_tqdm.py", line 439, in _decr_instances
> >   File "/Users/gurersalan/miniconda3/envs/text_Generation/lib/python3.7/_weakrefset.py", line 109, in remove
> > KeyError: <weakref at 0x7fd9718f8770; to 'tqdm' at 0x7fd975ae2150>
> ```

do you have tensorflow installed?

**Comment by Belval** [comment]
@mgersalan the issue is that you have a file in the `images/` directory that is not an image (.DS_Store). It can be fixed but in the meantime you can just delete it.

**Comment by mgersalan** [comment]
Exactly! It was about the hidden .DS_Store file. It is resolved. Thank you.
