### ISSUE TITLE
hello, i change the font and have a error

### ISSUE THREAD

**Issue by tjpulfn** [Belval/TextRecognitionDataGenerator#25]
`The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/liufengnan/Desktop/TextRecognitionDataGenerator/TextRecognitionDataGenerator/run.py", line 392, in <module>
    main()
  File "/Users/liufengnan/Desktop/TextRecognitionDataGenerator/TextRecognitionDataGenerator/run.py", line 309, in main
    ), total=args.count):
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
OSError: broken file
`

**Comment by Belval** [comment]
1. Can you provide the font you used?
2. In what directory did you put it?
3. Can you provide the full command line used?

**Comment by tjpulfn** [comment]
first. i use the font "SourceHanSans-Normal.ttf" that in the project it is successful
and then i change a new font "Arial Unicode.ttf" and run.py, it has error , i put it in "cn" directory
ps： can i speak chinese???

**Comment by tjpulfn** [comment]
@Belval hello, the problem is solved! thank you

**Comment by Belval** [comment]
Glad you got it sorted out! I'm closing the issue but feel free to reopen it if you need any help.

ps: As much as I would love to, I never got the chance to learn Chinese :(
