### ISSUE TITLE
AttributeError: 'FreeTypeFont' object has no attribute 'getlength'  

### ISSUE THREAD

**Issue by Pavel-hb** [Belval/TextRecognitionDataGenerator#288]
After cloning the repository in Google Colab. When running the command. 
!python3 run.py -c 10
I get an error. How to fix it?

  0% 0/10 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "../trdg/data_generator.py", line 22, in generate_from_tuple
    cls.generate(*t)
  File "../trdg/data_generator.py", line 83, in generate
    stroke_fill,
  File "../trdg/computer_text_generator.py", line 46, in generate
    stroke_fill,
  File "../trdg/computer_text_generator.py", line 88, in _generate_horizontal_text
    space_width = int(get_text_width(image_font, " ") * space_width)
  File "../trdg/utils.py", line 141, in get_text_width
    return round(image_font.getlength(text))
AttributeError: 'FreeTypeFont' object has no attribute 'getlength'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 493, in <module>
    main()
  File "run.py", line 474, in main
    total=args.count,
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "../trdg/data_generator.py", line 22, in generate_from_tuple
    cls.generate(*t)
  File "../trdg/data_generator.py", line 83, in generate
    stroke_fill,
  File "../trdg/computer_text_generator.py", line 46, in generate
    stroke_fill,
  File "../trdg/computer_text_generator.py", line 88, in _generate_horizontal_text
    space_width = int(get_text_width(image_font, " ") * space_width)
  File "../trdg/utils.py", line 141, in get_text_width
    return round(image_font.getlength(text))
AttributeError: 'FreeTypeFont' object has no attribute 'getlength'

**Comment by khawar-islam** [comment]
Also getting same error

**Comment by javohirss** [comment]
Also getting same error. Installing Pillow=9.2.0 doesnt solve problem

**Comment by Mousasan97** [comment]
Hi!, I'm having the same issue, have you fixed it?

**Comment by Pavel-hb** [comment]
Yeah everything worked after the Pillow library update.
# update the version of the PIL library so that there is no error when
working with the trdg library, restart the runtime environment.
!pip install --upgrade Pillow

ср, 28 дек. 2022 г. в 02:58, Mousasan97 ***@***.***>:

**Comment by Pavel-hb** [comment]
.# update the version of the PIL library so that there is no error when working with the trdg library, restart the runtime environment.
!pip install --upgrade Pillow
import PIL
print('PIL version:', PIL.__version__) # --> PIL version: 9.3.0
.# Clone the repository  
!git clone https://github.com/Belval/TextRecognitionDataGenerator
.# Install dependencies
!pip3 install -r /content/TextRecognitionDataGenerator/requirements.txt #requirements.txt
Installed in Google Colab in this order, everything ran.
