### ISSUE TITLE
Missing modules for handwritten text generation.

### ISSUE THREAD

**Issue by whiitees** [Belval/TextRecognitionDataGenerator#316]
When I use this command 'trdg -c 1000 -w 5 -f 64 -bl 4'

Ther is this error:
Missing modules for handwritten text generation.
  0%|                                                                                     | 0/1000 [00:00<?, ?it/s]Missing modules for handwritten text generation.
  0%|                                                                                     | 0/1000 [00:11<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\natan\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\natan\AppData\Local\Programs\Python\Python39\lib\site-packages\trdg\data_generator.py", line 22, in generate_from_tuple
    cls.generate(*t)
  File "C:\Users\natan\AppData\Local\Programs\Python\Python39\lib\site-packages\trdg\data_generator.py", line 72, in generate
    image, mask = computer_text_generator.generate(
  File "C:\Users\natan\AppData\Local\Programs\Python\Python39\lib\site-packages\trdg\computer_text_generator.py", line 36, in generate
    return _generate_horizontal_text(
  File "C:\Users\natan\AppData\Local\Programs\Python\Python39\lib\site-packages\trdg\computer_text_generator.py", line 107, in _generate_horizontal_text
    text_height = max([get_text_height(image_font, p) for p in splitted_text])
  File "C:\Users\natan\AppData\Local\Programs\Python\Python39\lib\site-packages\trdg\computer_text_generator.py", line 107, in <listcomp>
    text_height = max([get_text_height(image_font, p) for p in splitted_text])
  File "C:\Users\natan\AppData\Local\Programs\Python\Python39\lib\site-packages\trdg\utils.py", line 122, in get_text_height
    return image_font.getsize(text)[1]
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\natan\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\natan\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\natan\AppData\Local\Programs\Python\Python39\Scripts\trdg.exe\__main__.py", line 7, in <module>
  File "C:\Users\natan\AppData\Local\Programs\Python\Python39\lib\site-packages\trdg\run.py", line 438, in main
    for _ in tqdm(
  File "C:\Users\natan\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\Users\natan\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 870, in next
    raise value
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

I'am used a python 3.9.13

**Comment by pourmand1376** [comment]
Found the answer [here](https://github.com/tensorflow/models/issues/11040). 

```
pip install Pillow==9.5.0
```
