### ISSUE TITLE
osError: broken file

### ISSUE THREAD

**Issue by luckydog5** [Belval/TextRecognitionDataGenerator#48]
Traceback (most recent call last):
  File "run.py", line 340, in <module>
    main()
  File "run.py", line 328, in main
    ), total=args.count):
  File "/data/env/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 931, in __iter__
    for obj in iterable:
  File "/data/env/anaconda3/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
OSError: broken file
Exception ignored in: <bound method tqdm.__del__ of   0%|                                                 | 21/500000 [00:00<6:24:25, 21.68it/s]>
Traceback (most recent call last):
  File "/data/env/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 883, in __del__
  File "/data/env/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1088, in close
  File "/data/env/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 439, in _decr_instances
  File "/data/env/anaconda3/lib/python3.6/_weakrefset.py", line 109, in remove
KeyError: <weakref at 0x7f0af5879688; to 'tqdm' at 0x7f0bc8e1d0f0>

**Comment by Belval** [comment]
Unfortunately, the stack trace is obscured by the tqdm/multiprocessing part of TextRecognitionDataGenerator. Can you provide the invocation you used and the special font/dict if any?

**Comment by luckydog5** [comment]
Thanks, i've solved it. It's the font error.

**Comment by Belval** [comment]
Glad you got it sorted out! Closing.

**Comment by joei1994** [comment]
@luckydog5  I face the same error. Could you explain how to fix it?

**Comment by cty123** [comment]
If you're using MACOS then make sure you delete .DS_Store, otherwise it simply treats the .DS_Store file as a font library which raises the error. @Belval You might wanna add file ext checking before loading the fonts.
