### ISSUE TITLE
run.py crashes when generating dataset for new non- latin language

### ISSUE THREAD

**Issue by GalMoore** [Belval/TextRecognitionDataGenerator#64]
`text_rec_task) galmoore@Gals-MacBook-Pro:~/anaconda/envs/text_rec_task/TextRecognitionDataGenerator/TextRecognitionDataGenerator$ python run_script.py

Missing modules for handwritten text generation.

args count10

100%|██████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 56.40it/s]

Missing modules for handwritten text generation.

args count10

100%|█████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 102.17it/s]

Missing modules for handwritten text generation.

args count10

100%|██████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 67.58it/s]

Missing modules for handwritten text generation.

args count10

100%|█████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 108.27it/s]

Missing modules for handwritten text generation.

args count10

100%|██████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 70.82it/s]

Missing modules for handwritten text generation.

args count10

  0%|                                                                   | 0/10 [00:00<?, ?it/s]multiprocessing.pool.RemoteTraceback: 

"""

Traceback (most recent call last):

  File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/multiprocessing/pool.py", line 119, in worker

    result = (True, func(*args, **kwds))

  File "/Users/galmoore/anaconda/envs/text_rec_task/TextRecognitionDataGenerator/TextRecognitionDataGenerator/data_generator.py", line 23, in generate_from_tuple

    cls.generate(*t)

  File "/Users/galmoore/anaconda/envs/text_rec_task/TextRecognitionDataGenerator/TextRecognitionDataGenerator/data_generator.py", line 42, in generate

    image = computer_text_generator.generate(text, font, text_color, size, orientation, space_width, fit)

  File "/Users/galmoore/anaconda/envs/text_rec_task/TextRecognitionDataGenerator/TextRecognitionDataGenerator/computer_text_generator.py", line 7, in generate

    return _generate_horizontal_text(text, font, text_color, font_size, space_width, fit)

  File "/Users/galmoore/anaconda/envs/text_rec_task/TextRecognitionDataGenerator/TextRecognitionDataGenerator/computer_text_generator.py", line 14, in _generate_horizontal_text

    image_font = ImageFont.truetype(font=font, size=font_size)

  File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/site-packages/PIL/ImageFont.py", line 280, in truetype

    return FreeTypeFont(font, size, index, encoding, layout_engine)

  File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/site-packages/PIL/ImageFont.py", line 145, in __init__

    layout_engine=layout_engine)

OSError: unknown file format

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "run.py", line 376, in <module>

    main()

  File "run.py", line 364, in main

    ), total=args.count):

  File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1005, in __iter__

    for obj in iterable:

  File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/multiprocessing/pool.py", line 735, in next

    raise value

OSError: unknown file format

Missing modules for handwritten text generation.

args count10

100%|██████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 70.12it/s]

Missing modules for handwritten text generation.

args count10

100%|██████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 44.38it/s]

Missing modules for handwritten text generation.

args count10

100%|██████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 37.21it/s]

Missing modules for handwritten text generation.

args count10

100%|██████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 53.60it/s]`

**Comment by Belval** [comment]
Can you send me the font + dictionary that you are using? I'd be glad to troubleshoot it on my side if I have a test case.

**Comment by GalMoore** [comment]
Thanks, much appreciated. You can grab the dictionary + font here (as well as the data_generator.py and run.py scripts I am using). Look forward to hearing from you! https://github.com/GalMoore/text_generation_task

**Comment by GalMoore** [comment]
Hey @Belval any chance reproducing this?

**Comment by Belval** [comment]
Not yet sorry, I just finished my midterm exams so I should be able to test it shortly.

**Comment by Belval** [comment]
It seems to work on my side with the font and dict you provided?

![חצאית_5](https://user-images.githubusercontent.com/5399488/59466524-86d62680-8dfb-11e9-91db-a0871aa6cfcf.jpg)
![כסף_7](https://user-images.githubusercontent.com/5399488/59466525-86d62680-8dfb-11e9-99f1-97c826a92d46.jpg)
![מוח_2](https://user-images.githubusercontent.com/5399488/59466526-86d62680-8dfb-11e9-9a67-cd8eb159a1a8.jpg)
![מתוק_3](https://user-images.githubusercontent.com/5399488/59466527-86d62680-8dfb-11e9-8b71-309fd5e8a103.jpg)
![סטודנט_6](https://user-images.githubusercontent.com/5399488/59466528-876ebd00-8dfb-11e9-8fee-03ba9d610bad.jpg)
![צפון_4](https://user-images.githubusercontent.com/5399488/59466530-88075380-8dfb-11e9-95e3-8457a6012963.jpg)
![קינואה_8](https://user-images.githubusercontent.com/5399488/59466531-88075380-8dfb-11e9-8042-4118b8cee47f.jpg)
![רב_1](https://user-images.githubusercontent.com/5399488/59466532-88075380-8dfb-11e9-8302-3bfb41d81148.jpg)
![שכונה_9](https://user-images.githubusercontent.com/5399488/59466533-88075380-8dfb-11e9-9295-fd41b2b3cbc7.jpg)
![שניצל_0](https://user-images.githubusercontent.com/5399488/59466534-88075380-8dfb-11e9-94cb-7346bce09a85.jpg)

Although the filenames are inverted which would have to be fixed. I think I'll add it to the official repo, this is pretty nice.

**Comment by Belval** [comment]
So I might have found something, in the `he.txt` file, there is an empty line which causes `run.py` to panic because the image has no width. I'll fix that.

As for the OSError you encounter, I am unable to reproduce it on Ubuntu 18.04 with Python 3.7. I generated over 100 000 samples with multithreading activated (to see if it was a concurrency issue) and I didn't hit anything.

What is your OS?
What is your Python version?

**Comment by GalMoore** [comment]
Thanks, I've tried on MacOS Mojave in an Anaconda environment with Python 3.6.8 and on an Ubuntu 18.04 with similar setup. This is how it looks when I run run.py with the args you used above:

python3 run.py -c 50 -w 1 -l he
Missing modules for handwritten text generation.
args count50
 16%|███████                                     | 8/50 [00:00<00:00, 78.26it/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/galmoore/anaconda/envs/text_rec_task/TextRecognitionDataGenerator/TextRecognitionDataGenerator/data_generator.py", line 23, in generate_from_tuple
    cls.generate(*t)
  File "/Users/galmoore/anaconda/envs/text_rec_task/TextRecognitionDataGenerator/TextRecognitionDataGenerator/data_generator.py", line 42, in generate
    image = computer_text_generator.generate(text, font, text_color, size, orientation, space_width, fit)
  File "/Users/galmoore/anaconda/envs/text_rec_task/TextRecognitionDataGenerator/TextRecognitionDataGenerator/computer_text_generator.py", line 7, in generate
    return _generate_horizontal_text(text, font, text_color, font_size, space_width, fit)
  File "/Users/galmoore/anaconda/envs/text_rec_task/TextRecognitionDataGenerator/TextRecognitionDataGenerator/computer_text_generator.py", line 14, in _generate_horizontal_text
    image_font = ImageFont.truetype(font=font, size=font_size)
  File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/site-packages/PIL/ImageFont.py", line 280, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/site-packages/PIL/ImageFont.py", line 145, in __init__
    layout_engine=layout_engine)
OSError: unknown file format
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 376, in <module>
    main()
  File "run.py", line 364, in main
    ), total=args.count):
  File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1005, in __iter__
    for obj in iterable:
  File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
OSError: unknown file format

**Comment by parksunwoo** [comment]
I added support for korean with some .ttf fonts and a dictionary. The adjusted run.py and datagenerator.py files run and work till they crash also.
Look forward to hearing from you~

https://github.com/parksunwoo/TextRecognitionDataGenerator/tree/master/TextRecognitionDataGenerator/fonts/ko/
https://github.com/parksunwoo/TextRecognitionDataGenerator/tree/master/TextRecognitionDataGenerator/dicts/ko.txt

**Comment by Belval** [comment]
This seems to be a very nasty bug with Pillow unfortunately. I'm looking into ways to either fix or circumvent the issue. You can follow the fix progression here: https://github.com/python-pillow/Pillow/issues/3066

**Comment by parksunwoo** [comment]
It's a temporary fix, but it's quick to create the data,

```bash
while true; do python run.py -w 5 -f 64 -l ko; sleep 1; done;
```

**Comment by SungmanHong** [comment]
I just succeed 

`python run.py -w 5 -f 64
`
however, when I run below command in windows,

` python run.py -w 5 -f 64 -l ko`

I meet 

```
2020-08-07 16:52:00.595597: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll n
ot found
2020-08-07 16:52:00.604293: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
  0%|                                                                                                                                           | 0/1000 [00:00<?, ?it/s]2
020-08-07 16:52:06.775092: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll no
t found
2020-08-07 16:52:06.784047: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\ocr_kor-master\ocr_kor-master\data\generator\TextRecognitionDataGenerator\data_generator.py", line 22, in generate_from_tuple
    cls.generate(*t)
  File "D:\ocr_kor-master\ocr_kor-master\data\generator\TextRecognitionDataGenerator\data_generator.py", line 40, in generate
    image = computer_text_generator.generate(text, font, text_color, size, orientation, space_width, fit)
  File "D:\ocr_kor-master\ocr_kor-master\data\generator\TextRecognitionDataGenerator\computer_text_generator.py", line 7, in generate
    return _generate_horizontal_text(text, font, text_color, font_size, space_width, fit)
  File "D:\ocr_kor-master\ocr_kor-master\data\generator\TextRecognitionDataGenerator\computer_text_generator.py", line 14, in _generate_horizontal_text
    image_font = ImageFont.truetype(font=font, size=font_size)
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\ImageFont.py", line 642, in truetype
    return freetype(font)
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\ImageFont.py", line 639, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\ImageFont.py", line 188, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: unknown file format
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 374, in <module>
    main()
  File "run.py", line 362, in main
    ), total=args.count):
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\site-packages\tqdm\std.py", line 1104, in __iter__
    for obj in iterable:
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 735, in next
    raise value
OSError: unknown file format
  0%|                             
```                 

It seems OSError cause I run this code in windows?? should I run this code on linux?

**Comment by SungmanHong** [comment]
> It's a temporary fix, but it's quick to create the data,
> 
> ```shell
> while true; do python run.py -w 5 -f 64 -l ko; sleep 1; done;
> ```

Korean:
어떻게 고치는지 알 수 있을까요?? windows에서 저걸 돌리기 위해 어떻게 해야 할까요...?ㅠ

**Comment by SungmanHong** [comment]
> Thanks, I've tried on MacOS Mojave in an Anaconda environment with Python 3.6.8 and on an Ubuntu 18.04 with similar setup. This is how it looks when I run run.py with the args you used above:
> 
> python3 run.py -c 50 -w 1 -l he
> Missing modules for handwritten text generation.
> args count50
> 16%|███████ | 8/50 [00:00<00:00, 78.26it/s]multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
> File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/multiprocessing/pool.py", line 119, in worker
> result = (True, func(*args, **kwds))
> File "/Users/galmoore/anaconda/envs/text_rec_task/TextRecognitionDataGenerator/TextRecognitionDataGenerator/data_generator.py", line 23, in generate_from_tuple
> cls.generate(*t)
> File "/Users/galmoore/anaconda/envs/text_rec_task/TextRecognitionDataGenerator/TextRecognitionDataGenerator/data_generator.py", line 42, in generate
> image = computer_text_generator.generate(text, font, text_color, size, orientation, space_width, fit)
> File "/Users/galmoore/anaconda/envs/text_rec_task/TextRecognitionDataGenerator/TextRecognitionDataGenerator/computer_text_generator.py", line 7, in generate
> return _generate_horizontal_text(text, font, text_color, font_size, space_width, fit)
> File "/Users/galmoore/anaconda/envs/text_rec_task/TextRecognitionDataGenerator/TextRecognitionDataGenerator/computer_text_generator.py", line 14, in _generate_horizontal_text
> image_font = ImageFont.truetype(font=font, size=font_size)
> File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/site-packages/PIL/ImageFont.py", line 280, in truetype
> return FreeTypeFont(font, size, index, encoding, layout_engine)
> File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/site-packages/PIL/ImageFont.py", line 145, in **init**
> layout_engine=layout_engine)
> OSError: unknown file format
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "run.py", line 376, in
> main()
> File "run.py", line 364, in main
> ), total=args.count):
> File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1005, in **iter**
> for obj in iterable:
> File "/Users/galmoore/anaconda/envs/text_rec_task/lib/python3.6/multiprocessing/pool.py", line 735, in next
> raise value
> OSError: unknown file format

Hi, I just got some issue, it maybe caused by invalid ttf error. please check the ttf file in the font folder. just use only 1 ttf file for test. if not working, download trustable ttf file and replace it. 

ref : https://github.com/parksunwoo/ocr_kor/issues/11 (korean)

**Comment by Belval** [comment]
The included fonts does not seem to be valid. I am overdue for testing all the fonts in the repo and making sure that they all work. I'll try to find some bandwidth to do that.

In your Korean message, you seem to be missing the cv2 dependency. You will want to install it.
