### ISSUE TITLE
Error when generate handwritten text

### ISSUE THREAD

**Issue by HuFBH** [Belval/TextRecognitionDataGenerator#99]
Hi,i got this error.
How can i get handwritten text images?
Thx a lot.
![image](https://user-images.githubusercontent.com/47581857/65211472-72c45400-dad1-11e9-8e5b-e8e0729c1e4e.png)

**Comment by Belval** [comment]
Hi!

Can you give me a code snippet or the invocation you did? Also, do note that handwritten generation is only available in English.

**Comment by HuFBH** [comment]
Oh,right.
I try it again as shown below:
here i made a soft link to ./trdg/handwritten_model,and it's virtual environment.
![image](https://user-images.githubusercontent.com/47581857/65367203-7fc37d80-dc60-11e9-90b5-5aa90165cd01.png)

**Comment by HuFBH** [comment]
More information here:

0%|                                                                | 0/10 [00:00<?, ?it/s]WARNING:tensorflow:From /data/2014/PC_HuFBH/AI_text_Recognized/TextRecognitionDataGenerator/trdg/handwritten_text_generator.py:154: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /data/2014/PC_HuFBH/AI_text_Recognized/TextRecognitionDataGenerator/trdg/handwritten_text_generator.py:155: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From /data/2014/PC_HuFBH/AI_text_Recognized/TextRecognitionDataGenerator/trdg/handwritten_text_generator.py:156: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-09-21 11:08:51.449682: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-09-21 11:08:51.454290: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2019-09-21 11:08:51.454848: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e0cb370e20 executing computations on platform Host. Devices:
2019-09-21 11:08:51.454869: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /data/2014/PC_HuFBH/AI_text_Recognized/TextRecognitionDataGenerator/trdg/handwritten_text_generator.py:157: The name tf.train.import_meta_graph is deprecated. Please use tf.compat.v1.train.import_meta_graph instead.

WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/pytorch_huf/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-09-21 11:08:52.424797: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
WARNING:tensorflow:From /data/2014/PC_HuFBH/AI_text_Recognized/TextRecognitionDataGenerator/trdg/handwritten_text_generator.py:60: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_huf/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/data/2014/PC_HuFBH/AI_text_Recognized/TextRecognitionDataGenerator/trdg/data_generator.py", line 25, in generate_from_tuple
    cls.generate(*t)
  File "/data/2014/PC_HuFBH/AI_text_Recognized/TextRecognitionDataGenerator/trdg/data_generator.py", line 65, in generate
    image = handwritten_text_generator.generate(text, text_color)
  File "/data/2014/PC_HuFBH/AI_text_Recognized/TextRecognitionDataGenerator/trdg/handwritten_text_generator.py", line 193, in generate
    "RGBA", canvas.get_width_height(), canvas.buffer_rgba()
  File "/home/ubuntu/anaconda3/envs/pytorch_huf/lib/python3.6/site-packages/PIL/Image.py", line 2546, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/home/ubuntu/anaconda3/envs/pytorch_huf/lib/python3.6/site-packages/PIL/Image.py", line 830, in frombytes
    s = d.decode(data)
TypeError: argument 1 must be read-only bytes-like object, not memoryview
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_huf/bin/trdg", line 380, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/pytorch_huf/bin/trdg", line 364, in main
    total=args.count,
  File "/home/ubuntu/anaconda3/envs/pytorch_huf/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1060, in __iter__
    for obj in iterable:
  File "/home/ubuntu/anaconda3/envs/pytorch_huf/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
TypeError: argument 1 must be read-only bytes-like object, not memoryview
  0%|

**Comment by Belval** [comment]
I'll troubleshoot it tomorrow, thank you for the info.

**Comment by melnikoleg** [comment]
I solve this problem by installing tensorflow==1.13.1

**Comment by NguyenViet123** [comment]
I solve this problem by edit code at line 193 in handwritten_text_generator.py by:
image = Image.frombytes(
                "RGBA", canvas.get_width_height(), canvas.buffer_rgba().tobytes()
)

**Comment by HuFBH** [comment]
> I solve this problem by edit code at line 193 in handwritten_text_generator.py by:
> image = Image.frombytes(
> "RGBA", canvas.get_width_height(), canvas.buffer_rgba().tobytes()
> )
> 
> and at line 81 in data_generator.py:
> if not is_handwritten:
> rotated_mask = mask.rotate(
> skewing_angle if not random_skew else random_angle, expand=1
> )
> else:
> rotated_mask = Image.new('L', image.size)

yeah,it works for me now.so long it went,that i almost forget it.thanks a lot.
